In [ ]:
import torch #Tensor
import numpy as np #Array
import pandas as pd
import matplotlib.pyplot
print(torch.__version__)

2.1.0+cu121


# Introduction to Tensors

## Creating tensors

PyTorch creating tensor by torch.tensor()

In [ ]:
#scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [ ]:
scalar.ndim

0

In [ ]:
# Mengembalikan tensor ke python int
scalar.item()

8

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor1 = torch.tensor([[[1,3],
                       [4,5],
                        [8,9]],
                        [[10,1],
                         [9,8],
                         [10,7]]])
tensor1.shape

torch.Size([2, 3, 2])

In [ ]:
tensor1[1][2]

tensor([10,  7])

In [ ]:
tensor1.ndim

3

In [ ]:
tensor1[1,2,0]

tensor(10)

# Random Tensors

kenapa?

Karena banyak neural network yang memulai dengan tensor yang penuh dengan angka random dan angka random disesuaikan untuk merepresentasikan data lebih baik lagi.

start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [ ]:
# Buat random tensor dengan ukuran (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2748, 0.9538, 0.6981, 0.1420],
        [0.0806, 0.6275, 0.7477, 0.4334],
        [0.2979, 0.7745, 0.6621, 0.3756]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros and Ones

In [ ]:
 zeros = torch.zeros(3,4)
 zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating a range of tensors and tensors-like

In [ ]:
#use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

**Note:** Tensor datatype adalah salah satu 3 error besar yang akan ditemui dengan PyTorch & deep learning:

1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [ ]:
 float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype = None, #Apa tipe data tensor
                                device = None, #Apa device yang bekerja pada tensor
                                requires_grad = False)#Apakah dapat melacak gradien
 float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
float_32_mat = torch.tensor([[3,4,5],
                             [8,10,11],
                             [9,12,17]]).type(torch.float64)
float_64_mat = torch.tensor([[7,8,9],
                             [12,18,13],
                             [19,20,21]]).type(torch.float64)

float_32_mat @ float_64_mat

tensor([[164., 196., 184.],
        [385., 464., 433.],
        [530., 628., 594.]], dtype=torch.float64)

In [ ]:
int_32_tensor = torch.tensor([1,2,3], dtype=torch.long)
int_32_tensor

tensor([1, 2, 3])

In [ ]:
float_16_tensor*int_32_tensor

tensor([ 3., 12., 27.], dtype=torch.float16)

# Getting Information from Tensor (attributes)

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [ ]:
# create a tensor
some_tensor = torch.rand(3,4).to(device)
some_tensor

tensor([[0.9166, 0.2994, 0.8576, 0.3454],
        [0.1674, 0.2661, 0.1272, 0.6103],
        [0.2214, 0.7886, 0.9871, 0.5601]], device='cuda:0')

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9166, 0.2994, 0.8576, 0.3454],
        [0.1674, 0.2661, 0.1272, 0.6103],
        [0.2214, 0.7886, 0.9871, 0.5601]], device='cuda:0')
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cuda:0


### Manipulating Tensors (tensor operatios)

Operasi Tensor

 * Pertambahan
 * Pengurangan
 * Perkalian (element-wise)
 * Pembagian
 * Perkalian Matriks

In [ ]:
# Create tensor
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matriks Multiplication

* Element-wise

* Matrix Multiplication (dot product)

Dua aturan perkalian matriks:

1. The **inner dimensions** must match:
  * `(3,2) @ (3,2)` ga bisa
  * `(2,3) @ (3,2)` bisa
  * `(3,2) @ (2,3)` bisa

2. Hasil shape perkalian matriks adalah **outer dimensions**:

  * `(2,3) @ (3,2)` -> (2,2)
  * `(3,2) @ (2,3)` -> (3,3)


In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.4314, 0.7318, 0.9124],
        [0.6055, 0.9673, 1.4926],
        [0.4839, 0.7986, 1.1019]])

In [ ]:
# Perkalian Matriks element wise
print(tensor, '*', tensor)
print(f"equals = {tensor*tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
equals = tensor([1, 4, 9])


In [ ]:
# Perkalian Matriks
torch.matmul(tensor,tensor)

tensor(14)

### One common error for deep learning is tensor shape

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

In [ ]:
#torch.matmul(tensor_A, tensor_B)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

Cara ngebenerinnya adalah dengan cara memanipulasi tensor dengan **transpose**

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Find min, max, mean, sum etc (aggregations)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# SUM
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> return index minimum value
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

### Reshaping, stacking, squeexing and unsqueezing tensors

* Reshaping -> Merubah shape tensor ke shape tensor yang didefinisikan
* View -> mengembalikan tampilan tensor input dengan bentuk tertentu tetapi tetap sama dengan tensor aslinya
* Squeeze -> menghilangkan semua `1` dimensi target sensor
* Unsqueeze -> Menambahkan `1` dimensi ke target tensor
* Permute -> mengembalikan tampilan input dengan dimensi yang diubah (swapped) dengan cara tertentu

In [ ]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#reshape
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Mengubah z berarti mengubah x (karena view tensor berbagi memori yang sama dengan tensor original)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensor
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
#torch.squeeze() - remove all single dimensions from a target tensor
x_reshaped = z
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) #[height, width, colour_channels]

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

# Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPY

In [ ]:
#Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][0][1]

tensor(2)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
print(x[0][2][2])

#Index on x to return 3,6,9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch

In [ ]:
# Numpy array to tensor
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #warning: default dtype float64 not must convert dtype
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() #default dtype float32
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to `numpy_tensor`
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out random)

In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> ...

To reduce the randomness in neural networks and PyTorch comes the concept of **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1776, 0.2915, 0.9697, 0.5129],
        [0.2157, 0.6321, 0.3296, 0.9075],
        [0.7635, 0.9909, 0.7830, 0.5636]])
tensor([[0.5944, 0.5057, 0.6573, 0.2508],
        [0.6636, 0.2904, 0.2911, 0.7892],
        [0.0178, 0.7352, 0.6736, 0.5990]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

#Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

### 1. Getting GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investmens of purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit setting

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on GPU

The reason we want our tensors/models on the GPU because using a GPU results in faster computations.

In [ ]:
tensor = torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
#tensor_on_gpu.numpy()

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercise & Extra Curriculum

In [ ]:
#1. Create random tensor with shape (7,7)
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

In [ ]:
#2.
random_tensor_A = torch.rand(1,7)
torch.matmul(random_tensor, random_tensor_A.T)

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])

In [ ]:
torch.manual_seed(0)
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [ ]:
torch.manual_seed(0)
random_tensor_A = torch.rand(1,7)

torch.matmul(random_tensor, random_tensor_A.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [ ]:
torch.cuda.manual_seed(1234)

In [ ]:
torch.manual_seed(1234)
random_tensor_A = torch.rand(2,3).to(device)

random_tensor_B = torch.rand(2,3).to(device)
random_tensor_A, random_tensor_B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [ ]:
matmul = torch.matmul(random_tensor_A,random_tensor_B.T)
matmul

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [ ]:
matmul.max(), matmul.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [ ]:
matmul.argmax(), matmul.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [ ]:
torch.manual_seed(7)
tensor_1 = torch.rand(1,1,1,10)
print(f"tensor_1 : {tensor_1}")
print(f"tensor_1 shape : {tensor_1.shape}")

tensor_1_squeezed = tensor_1.squeeze()
print(f"tensor_1_squeezed : {tensor_1_squeezed}")
print(f"tensor_1_squeezed shape : {tensor_1_squeezed.shape}")

tensor_1 : tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor_1 shape : torch.Size([1, 1, 1, 10])
tensor_1_squeezed : tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
tensor_1_squeezed shape : torch.Size([10])
