# Linear Regression Basic

In [ ]:
import numpy
import torch
import pandas as pd
import torch.nn as nn

In [ ]:
df = pd.read_csv("daya_listrik.csv")

In [ ]:
df

No.    V  I (Ampere)  y = P (watt)  x = VI(watt)
0    1   10       0.068          0.69          0.68
1    2   20       0.087          1.74          1.74
2    3   30       0.099          3.00          2.97
3    4   40       0.112          4.49          4.48
4    5   50       0.124          6.20          6.20
5    6   60       0.135          8.09          8.10
6    7   70       0.145         10.17         10.15
7    8   80       0.155         12.36         12.40
8    9   90       0.166         14.84         14.94
9   10  100       0.174         17.49         17.40

In [ ]:
x = df["x = VI(watt)"].values
x

array([ 0.68,  1.74,  2.97,  4.48,  6.2 ,  8.1 , 10.15, 12.4 , 14.94,
       17.4 ])

In [ ]:
y = df["y = P (watt)"].values
y

array([ 0.69,  1.74,  3.  ,  4.49,  6.2 ,  8.09, 10.17, 12.36, 14.84,
       17.49])

## Ubah Numpy to Tensor

In [ ]:
x = torch.from_numpy(x).unsqueeze(0).type(torch.float32)
y = torch.from_numpy(y).unsqueeze(-1).type(torch.float32)
print(x)
print(y)

tensor([[ 0.6800,  1.7400,  2.9700,  4.4800,  6.2000,  8.1000, 10.1500, 12.4000,
         14.9400, 17.4000]])
tensor([[ 0.6900],
        [ 1.7400],
        [ 3.0000],
        [ 4.4900],
        [ 6.2000],
        [ 8.0900],
        [10.1700],
        [12.3600],
        [14.8400],
        [17.4900]])


## Membuat Weight dan Bias

In [ ]:
w = torch.rand(1,1, requires_grad=True)
b = torch.rand(1, requires_grad=True)
print(w)
print(b)

tensor([[0.3864]], requires_grad=True)
tensor([0.4333], requires_grad=True)


## Model Regresi Linear Biasa

In [ ]:
def model(x):
  return x.t() @ w + b

## Hasil Prediksi

In [ ]:
preds = model(x)
preds

tensor([[0.6961],
        [1.1057],
        [1.5811],
        [2.1646],
        [2.8293],
        [3.5635],
        [4.3558],
        [5.2253],
        [6.2069],
        [7.1575]], grad_fn=<AddBackward0>)

## Menghitung Loss

In [ ]:
criterion = nn.MSELoss()
loss = criterion(preds,y)
loss

tensor(30.5675, grad_fn=<MseLossBackward0>)

## Menghitung Gradien

In [ ]:
loss.backward()

In [ ]:
print(w)
print(w.grad)

tensor([[0.3864]], requires_grad=True)
tensor([[-105.9087]])


In [ ]:
print(b)
print(b.grad)

tensor([0.4333], requires_grad=True)
tensor([-8.8369])


In [ ]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0.]])
tensor([0.])


In [ ]:
preds = model(x)
print(preds)

tensor([[0.6961],
        [1.1057],
        [1.5811],
        [2.1646],
        [2.8293],
        [3.5635],
        [4.3558],
        [5.2253],
        [6.2069],
        [7.1575]], grad_fn=<AddBackward0>)


In [ ]:
loss = criterion(preds,y)
loss

tensor(30.5675, grad_fn=<MseLossBackward0>)

In [ ]:
loss.backward()

In [ ]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
print(w)

tensor([[0.3875]], requires_grad=True)


In [ ]:
preds = model(x)
loss = criterion(preds, y)
print(loss)

tensor(30.4546, grad_fn=<MseLossBackward0>)


## Train Linear Regression 100 epochs

In [ ]:
for i in range(100):
    preds = model(x)
    loss = criterion(preds, y)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [ ]:
preds = model(x)
loss = criterion(preds, y)
print(loss)

tensor(21.0434, grad_fn=<MseLossBackward0>)


In [ ]:
preds

tensor([[0.7706],
        [1.2838],
        [1.8792],
        [2.6102],
        [3.4428],
        [4.3626],
        [5.3550],
        [6.4442],
        [7.6738],
        [8.8646]], grad_fn=<AddBackward0>)